#!/usr/bin/env node

/* eslint no-continue: 0 */

const { join } = require('path');
const { pipe, through } = require('mississippi');
const _ = require('lodash');
const { sync: rimrafSync } = require('rimraf');
const { length, nearestPointOnLine } = require('@turf/turf');
const { point } = require('@turf/helpers');

const levelup = require('levelup');
const leveldown = require('leveldown');
const encode = require('encoding-down');

const KILOMETERS = {
  units: 'kilometers'
};

const SHST_GEOGRAPHY_DB = join(
  __dirname,
  '../../data/sharedstreets/shst_tiles_leveldb/shstGeographyDB'
);

const SHST_MATCHED_RIS_DB = join(
  __dirname,
  '../../data/ris/shst_matched_leveldb/shstMatchedRISSegments'
);

const TARGET_MAPS_SEGEMENT_OFFSETS_DB = join(
  __dirname,
  'targetMapsSegmentOffsets'
);

const shstGeographyDB = levelup(
  encode(leveldown(SHST_GEOGRAPHY_DB), { valueEncoding: 'json' })
);

const shstMatchedRISSegmentsDB = levelup(
  encode(leveldown(SHST_MATCHED_RIS_DB), { valueEncoding: 'json' })
);

const targetMapsSegmentsOffsetsDB = levelup(
  encode(leveldown(TARGET_MAPS_SEGEMENT_OFFSETS_DB), { valueEncoding: 'json' })
);

pipe(
  shstMatchedRISSegmentsDB.createValueStream(),
  through.obj(async function loader(matches, $, cb) {
    const geometryIds = _(matches)
      .map('properties.shstGeometryId')
      .uniq()
      .filter()
      .value();

    const shstGeometries = (await Promise.all(
      geometryIds.map(async id => {
        try {
          return await shstGeographyDB.get(id);
        } catch (err) {
          if (err.type === 'NotFoundError') {
            console.error(
              `WARNING: no geometry found in shstGeographyDB for ${id}`
            );
            return null;
          }
          console.error('shstGeographyDB.get');
          throw new Error(err);
        }
      })
    )).reduce((acc, geom) => {
      if (geom) {
        acc[geom.properties.id] = geom;
      }
      return acc;
    }, {});

    const targetMapsSegmentOffsetsLists = (await Promise.all(
      geometryIds.map(async id => {
        let list;

        try {
          list = await targetMapsSegmentsOffsetsDB.get(id);
        } catch (err) {
          if (err.type === 'NotFoundError') {
            list = [];
          } else {
            console.error('targetMapsSegmentsOffsetsDB.get');
            throw new Error(err);
          }
        }

        return { id, list };
      })
    )).reduce((acc, { id, list }) => {
      acc[id] = list;
      return acc;
    }, {});

    for (let i = 0; i < matches.length; ++i) {
      const {
        properties: { shstGeometryId, pp_ogc_fid: fid },
        geometry: { coordinates }
      } = matches[i];

      const startPoint = point(_.first(coordinates));
      const endPoint = point(_.last(coordinates));

      const geom = shstGeometries[shstGeometryId];

      if (!geom) {
        continue;
      }

      // console.error(JSON.stringify({ startPoint, endPoint, geom }, null, 4));
      const offsetList = targetMapsSegmentOffsetsLists[shstGeometryId];

      const geomLength = length(geom, KILOMETERS);

      const snappedStart = nearestPointOnLine(geom, startPoint, KILOMETERS);
      const snappedEnd = nearestPointOnLine(geom, endPoint, KILOMETERS);

      const startDist = snappedStart.properties.location;
      const endDist = snappedEnd.properties.location;

      const segmentOffsets = {
        shstGeometryId,
        geomLength,
        target_map: 'RIS',
        target_map_id: fid,
        POFF: Math.min(startDist, endDist),
        NOFF: geomLength - Math.max(startDist, endDist)
      };

      // console.log(JSON.stringify(segmentOffsets, null, 4));

      offsetList.push(segmentOffsets);
    }

    const batchPut = geometryIds.map(id => ({
      type: 'put',
      key: id,
      value: _.uniqWith(targetMapsSegmentOffsetsLists[id], _.isEqual)
    }));

    try {
      await targetMapsSegmentsOffsetsDB.batch(batchPut);
    } catch (err) {
      console.error('ERROR in batch put');
      throw err;
    }

    return cb();
  }),
  err => {
    if (err) {
      console.error(
        'ERROR encountered while loading targetMapsSegmentOffsets DB.'
      );
      console.error(
        `    Deleting the corruped database at ${TARGET_MAPS_SEGEMENT_OFFSETS_DB}`
      );
      console.error();
      console.error(err);
      rimrafSync(TARGET_MAPS_SEGEMENT_OFFSETS_DB);
      process.exit(1);
    }
  }
);
