#!/usr/bin/env node

const { readFileSync, readdirSync } = require('fs');
const { join } = require('path');
const { pipe, through } = require('mississippi');
const turf = require('@turf/turf');
const _ = require('lodash');

const levelup = require('levelup');
const leveldown = require('leveldown');
const encode = require('encoding-down');

const MILES = { units: 'miles' };

const CONFLATION_PAIRINGS_DB = join(
  __dirname,
  '../../data/leveldb/',
  'conflationPairingsDB'
);

const conflationPairingsDB = levelup(
  encode(leveldown(CONFLATION_PAIRINGS_DB), {
    valueEncoding: 'json'
  })
);

const shapefilesDir = join(__dirname, '../../data/ris/county_geojson');

const getConflationStats = () => {
  const conflationStats = {};
  return new Promise((resolve, reject) =>
    pipe(
      conflationPairingsDB.createValueStream(),
      through.obj(function writer(feature, $, cb) {
        const ogc_fid = feature.properties.RIS;

        if (ogc_fid) {
          conflationStats[ogc_fid] = conflationStats[ogc_fid] || {};

          conflationStats[ogc_fid].length =
            conflationStats[ogc_fid].length || 0;
          conflationStats[ogc_fid].length += turf.length(feature, MILES);
        }

        return cb();
      }),
      err => {
        if (err) {
          return reject(err);
        }
        return resolve(conflationStats);
      }
    )
  );
};

(async () => {
  try {
    const conflationStats = await getConflationStats();

    const shapefiles = readdirSync(shapefilesDir);

    process.stdout.write(
      'ogc_fid,is_paired,metadata_length,shp_length,conflation_length,oneway_metadata_len_diff_ratio,oneway_shp_len_diff_ratio,twoway_metadata_len_diff_ratio,twoway_shp_len_diff_ratio\n'
    );

    for (let i = 0; i < shapefiles.length; ++i) {
      const shapefileName = shapefiles[i];

      const tmcShapeFile = JSON.parse(
        readFileSync(join(shapefilesDir, shapefileName))
      );

      for (let j = 0; j < tmcShapeFile.features.length; ++j) {
        const feature = tmcShapeFile.features[j];
        const {
          properties: { ogc_fid, Section_Length: miles }
        } = feature;

        const is_paired = conflationStats[ogc_fid] !== undefined;
        const metadata_length = _.round(miles, 5);
        const shp_length = _.round(turf.length(feature, MILES), 5);
        const conflation_length = conflationStats[ogc_fid]
          ? _.round(conflationStats[ogc_fid].length, 5)
          : 0;

        const oneway_metadata_len_diff_ratio = is_paired
          ? _.round((metadata_length - conflation_length) / shp_length, 5)
          : '';

        const oneway_shp_len_diff_ratio = is_paired
          ? _.round((shp_length - conflation_length) / shp_length, 5)
          : '';

        const twoway_metadata_len_diff_ratio = is_paired
          ? _.round((metadata_length - conflation_length / 2) / shp_length, 5)
          : '';

        const twoway_shp_len_diff_ratio = is_paired
          ? _.round((shp_length - conflation_length / 2) / shp_length, 5)
          : '';

        process.stdout.write(
          `${ogc_fid},${is_paired},${metadata_length},${shp_length},${conflation_length},${oneway_metadata_len_diff_ratio},${oneway_shp_len_diff_ratio},${twoway_metadata_len_diff_ratio},${twoway_shp_len_diff_ratio}\n`
        );
      }
    }
  } catch (err) {
    if (err) {
      console.error('ERROR');
      console.error(err);
    }
  }
})();
