#!/usr/bin/env node

const { readFileSync } = require('fs');
const { join } = require('path');
const { pipe, through } = require('mississippi');
const turf = require('@turf/turf');

const levelup = require('levelup');
const leveldown = require('leveldown');
const encode = require('encoding-down');

const CONFLATION_PAIRINGS_DB = join(__dirname, 'conflationPairingsDB');

const conflationPairingsDB = levelup(
  encode(leveldown(CONFLATION_PAIRINGS_DB), {
    valueEncoding: 'json'
  })
);

const tmcIsPrimary = JSON.parse(
  readFileSync(join(__dirname, './tmc_isprimary.json'))
);

const d = readFileSync(
  join(__dirname, '../../data/npmrds/county_geojson/npmrds.albany.geojson')
);

const tmcShapeFile = JSON.parse(d);

const pairedTMCLengths = {};

const getConflationPairingLengths = () =>
  new Promise((resolve, reject) =>
    pipe(
      conflationPairingsDB.createValueStream(),
      through.obj(function writer(feature, $, cb) {
        const tmcs = feature.properties.NPMRDS;
        if (tmcs) {
          for (let i = 0; i < tmcs.length; ++i) {
            const tmc = tmcs[i];
            pairedTMCLengths[tmc] = pairedTMCLengths[tmc] || 0;
            pairedTMCLengths[tmc] += turf.length(feature);
          }
        }

        return cb();
      }),
      err => {
        if (err) {
          return reject(err);
        }
        return resolve();
      }
    )
  );

(async () => {
  try {
    await getConflationPairingLengths();
    for (let i = 0; i < tmcShapeFile.features.length; ++i) {
      const feature = tmcShapeFile.features[i];
      const { properties } = feature;
      const { Tmc } = properties;
      properties.isPrimary = tmcIsPrimary[Tmc] !== 0;
      properties.isPaired = pairedTMCLengths[Tmc] !== undefined;
      if (properties.isPrimary) {
        properties.targetLength = turf.length(feature);
        properties.sourceLength = pairedTMCLengths[Tmc] || 0;
      }
      properties.conflationPasses = properties.isPrimary
        ? Math.abs(properties.targetLength - properties.sourceLength) /
            properties.sourceLength <
          0.05
        : !properties.isPaired;
    }

    console.log(JSON.stringify(tmcShapeFile));
  } catch (err) {
    if (err) {
      console.error('ERROR');
      console.error(err);
    }
  }
})();
