module.exports = {
  ERR_NO_SOURCE_NODES: 'ERR_NO_SOURCE_NODES',
  ERR_NUM_SOURCE_NODES_EXCEEDS_1: 'ERR_NUM_SOURCE_NODES_EXCEEDS_1',
  ERR_NUM_CHAINS_EXCEEDS_1: 'ERR_NUM_CHAINS_EXCEEDS_1',
  ERR_NUM_SOURCE_NODES_EXCEEDS_2: 'ERR_NUM_SOURCE_NODES_EXCEEDS_2',
  ERR_NUM_CHAINS_EXCEEDS_2: 'ERR_NUM_CHAINS_EXCEEDS_2'
};
