#!/bin/bash

set -e

usage() {
  cat <<EOM
  USAGE:
      The following two ENV variables are required:
          SHST_TILESET_DIR
          SHST_TILES_URL_BASE
EOM
}

if [ -z "$SHST_TILESET_DIR" ] || [ -z "$SHST_TILES_URL_BASE" ]; then
  usage
  exit 1
fi

if [ ! -d "$SHST_TILESET_DIR" ]; then
  echo "ERROR: No sharedstreets_tiles directory."
  exit 1
fi

LOCAL_REFERENCE_FILES="$(
  find "$SHST_TILESET_DIR" -type f -name '*reference*' -printf '%f\n' |
    sort -u
)"

REQUIRED_REFERENCE_FILES="$(
  find "$SHST_TILESET_DIR" -type f -printf '%f\n' |
    sed 's/geometry\|intersection\|metadata/reference/g' |
    sort -u
)"

if REFERENCE_FILES_TO_SCRAPE="$(
  grep --invert-match -f <( echo "$LOCAL_REFERENCE_FILES" | sed '/^$/d' ) <<< "$REQUIRED_REFERENCE_FILES" 
)"; then
  while read -r f; do
    curl --silent "$SHST_TILES_URL_BASE/$f" > "$SHST_TILESET_DIR/$f"
    sleep 1
  done <<< "$REFERENCE_FILES_TO_SCRAPE"
fi
