CREATE TABLE IF NOT EXISTS public.tmc_identification (
  tmc                      CHARACTER VARYING PRIMARY KEY,
  type                     CHARACTER VARYING,
  road                     CHARACTER VARYING,
  road_order               REAL,
  intersection             CHARACTER VARYING,
  tmclinear                INTEGER,
  country                  CHARACTER VARYING,
  state                    CHARACTER VARYING,
  county                   CHARACTER VARYING,
  zip                      CHARACTER VARYING,
  direction                CHARACTER VARYING,
  start_latitude           DOUBLE PRECISION,
  start_longitude          DOUBLE PRECISION,
  end_latitude             DOUBLE PRECISION,
  end_longitude            DOUBLE PRECISION,
  miles                    DOUBLE PRECISION,
  frc                      SMALLINT,
  border_set               CHARACTER VARYING,
  isprimary                SMALLINT,
  f_system                 SMALLINT,
  urban_code               INTEGER,
  faciltype                SMALLINT,
  structype                SMALLINT,
  thrulanes                SMALLINT,
  route_numb               INTEGER,
  route_sign               SMALLINT,
  route_qual               SMALLINT,
  altrtename               CHARACTER VARYING,
  aadt                     INTEGER,
  aadt_singl               INTEGER,
  aadt_combi               INTEGER,
  nhs                      SMALLINT,
  nhs_pct                  SMALLINT,
  strhnt_typ               SMALLINT,
  strhnt_pct               SMALLINT,
  truck                    SMALLINT,
  timezone_name            CHARACTER VARYING,
	active_start_date        DATE,
	active_end_date					 DATE
) WITH (fillfactor=100, autovacuum_enabled=false);
