#!/bin/bash

# shellcheck disable=SC2086

# Creates a partition of the osm file for the county

# osm2pgrouting requires xml format

# See:
#   https://github.com/pgRouting/osm2pgrouting#tips
#   https://wiki.openstreetmap.org/wiki/Osmosis
#   https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.47
#   https://wiki.openstreetmap.org/wiki/Osmosis/Polygon_Filter_File_Format

set -e
set -a

if [ "$#" -ne 4 ]; then
  (>&2 echo 'USAGE: You must provide three positional CLI argument:')
  (>&2 echo '         * 1st is the OSM file path')
  (>&2 echo '         * 2nd is the output file path')
  (>&2 echo '         * 3rd is the county name')
  (>&2 echo '         * 4th is the output format (xml or pbf)')
  (>&2 echo '  Output is written to STDOUT.')
  exit 1
fi

if [ ! -f "$1" ]; then
  (>&2 echo "ERROR: No file found at $1.")
  exit 1
fi

OSM_FILE="$( realpath "$1" )"

mkdir -p "$( dirname "$2" )"
touch "$2"

OUTF="$( realpath "$2" )"

COUNTY="${3,,}"

FORMAT="${4,,}"

if [ "$FORMAT" != 'xml' ] && [ "$FORMAT" != 'pbf' ]; then
  (>&2 echo "ERROR: Unrecognized the output format. The supported formats are xml and pbf.")
  exit 1
fi


pushd "$( dirname "${BASH_SOURCE[0]}" )/" >/dev/null

# source the database connection config.
. ../.env

SQL="
  SELECT
      ST_ConvexHull(
        ST_Collect(
          wkb_geometry
        )
      ) AS bpoly
    FROM public.npmrds_extended_shapefile
    WHERE (
      LOWER(REPLACE(county, ' ', '_')) = '$COUNTY'
    )
  ;
"

# Get the county bounding polygon as a string variable
BOUNDING_POLY="$COUNTY
tmc_convex_hull
$(
  ogr2ogr -s_srs EPSG:4326 -t_srs EPSG:4326 -f GeoJSON /vsistdout/ \
      "PG:host=${PGHOST} port=${PGPORT} user=${PGUSER} dbname=${PGDATABASE} password=${PGPASSWORD}" \
      -sql "$SQL" |
    jq '.features|map(.geometry.coordinates)|flatten[]' |
    paste -s -d' \n' |
    column -t |
    sed 's/^/  /'
)
END
END"

[ "$FORMAT" == 'xml' ] && FORMAT_FLAGS='--write-xml' || FORMAT_FLAGS='--write-pbf omitmetadata=true'

# highway=motorway,trunk,primary,secondary,tertiary,unclassified,residential,motorway_link,trunk_link,primary_link,secondary_link,tertiary_link,service,living_street\

osmosis \
  --read-pbf file="$OSM_FILE" \
  --tf accept-ways \
    highway=*\
  --bounding-polygon file=<( echo "$BOUNDING_POLY" ) completeWays=true \
  --used-node \
  $FORMAT_FLAGS file="$OUTF"

popd >/dev/null
