#!/bin/bash

set -e
set -a

cd "$( dirname "${BASH_SOURCE[0]}" )"

. ../.env

if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$PGDATABASE'" postgres )" != '1' ]; then
  psql -c 'CREATE DATABASE npmrds_routing;' postgres
fi

psql -c 'CREATE EXTENSION IF NOT EXISTS pgrouting CASCADE;'
psql -c 'CREATE EXTENSION IF NOT EXISTS hstore;'
