#!/bin/bash

set -e
set -a

cd "$( dirname "${BASH_SOURCE[0]}" )"

source ../.env

# pushd ../npmrds_etl/ >/dev/null

# ./upload-extended-npmrds-shapefile data/inrix_expanded.zip
# ./upload-tmc-identification data/TMC_Identification.csv

# popd >/dev/null

# pushd ../sharedstreets_conflation >/dev/null

./shstMatchNPMRDS 

# popd >/dev/null

./createCountyOSMSubset albany xml > data/osm/albany.osm
./createCountyOSMSubset albany pbf > data/osm/albany.osm.pbf
# 
# rm -rf sharedstreets_ndjson/*
# rm -rf sharedstreets_tiles/*
# 
# ./createSharedStreetsTileSet albany
# 
# ./tileSetToNDJSON \
#   --tilesetDir sharedstreets_tiles/albany \
#   --outputDir sharedstreets_ndjson \
#   --clean

# #### Database DDL ####
# 
# ./createDatabase
# 
# psql -f ./sql/createSharedStreetsTables.sql
# psql -f ./sql/createRoadInventorySystemTables.sql

#### Load Database ####

./load_osm_into_db data/osm/albany.osm

./load_tileset_ndjson_into_db \
  --tilesetNDJSONDir \
  ./sharedstreets_ndjson \
  --clean

./load_shst_matched_output_into_db \
  --clean \
  --shstTmcMatchesFile \
    ../sharedstreets_conflation/data/shst.albany.matched.geojson 

./loadRisGeodatabase ./data/ris/RISDuplicate.gdb
./extractAlbanyRISAsGeoJSON > ./data/ris/geojson/ris.albany.geojson

