#!/bin/bash

set -e

cd "$( dirname "${BASH_SOURCE[0]}" )"

mkdir -p ./data/ris/geojson

>&2 echo 'Extracting RIS Geodatabase to GeoJSON'

ogr2ogr -f GeoJSON /vsistdout/ ./data/ris/RISDuplicate.gdb \
  -sql "SELECT * FROM roadwayinventory where County_Name = 'ALBANY'" \
  > ./data/ris/geojson/ris.albany.geojson
