#!/bin/bash

# WARNING: This script deletes all pgrouting tables before loading the specified file.

set -e
set -a

if [ "$#" -ne 1 ]; then
  (>&2 echo 'USAGE: You must provide the OSM XML file path as the 1st and only CLI argument.')
  exit 1
fi

FILEPATH="$( realpath "$1" )"

if [ ! -f "$FILEPATH" ]; then
  (>&2 echo "ERROR: No file found at $FILEPATH")
  exit 1
fi

pushd "$( dirname "${BASH_SOURCE[0]}" )/" >/dev/null

. ../.env

psql -c 'CREATE SCHEMA IF NOT EXISTS pgrouting'

osm2pgrouting \
  --f "$FILEPATH" \
  --conf ./mapconfig_for_cars.xml \
  --dbname "$PGDATABASE" \
  --schema 'pgrouting' \
  --tags \
  --addnodes \
  --attributes \
  --host "$PGHOST" \
  --port "$PGPORT" \
  --username "$PGUSER" \
  --password "$PGPASSWORD" \
  --clean

popd >/dev/null
