#!/bin/bash

# The RIS Geodatabase uses EPSG:4269
#   https://spatialreference.org/ref/epsg/nad83/

# $ gdalsrsinfo RISDuplicate.gdb
# 
# PROJ.4 : '+proj=utm +zone=18 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs '
# 
# OGC WKT :
# PROJCS["NAD83 / UTM zone 18N",
#     GEOGCS["NAD83",
#         DATUM["North_American_Datum_1983",
#             SPHEROID["GRS 1980",6378137,298.257222101,
#                 AUTHORITY["EPSG","7019"]],
#             TOWGS84[0,0,0,0,0,0,0],
#             AUTHORITY["EPSG","6269"]],
#         PRIMEM["Greenwich",0,
#             AUTHORITY["EPSG","8901"]],
#         UNIT["degree",0.0174532925199433,
#             AUTHORITY["EPSG","9122"]],
#         AUTHORITY["EPSG","4269"]],
#     PROJECTION["Transverse_Mercator"],
#     PARAMETER["latitude_of_origin",0],
#     PARAMETER["central_meridian",-75],
#     PARAMETER["scale_factor",0.9996],
#     PARAMETER["false_easting",500000],
#     PARAMETER["false_northing",0],
#     UNIT["metre",1,
#         AUTHORITY["EPSG","9001"]],
#     AXIS["Easting",EAST],
#     AXIS["Northing",NORTH],
#     AUTHORITY["EPSG","26918"]]

set -e
set -a


RIS_GEODATABASE_ZIP=./data/ris/RISDuplicate.gdb.zip
RIS_GEODATABASE=./data/ris/RISDuplicate.gdb

if [ "$#" -ne 1 ]; then
  (>&2 echo "USAGE: You must specify the county name as the 1st and only CLI argument.")
  exit 1
fi

COUNTY="${1^^}"

if [ ! -d "$RIS_GEODATABASE" ]; then
  if [ -f "$RIS_GEODATABASE_ZIP" ]; then
    (>&2 echo "ERROR: No geodatabase found at $( realpath "$RIS_GEODATABASE" )")
    exit 1
  fi

  7za e "$RIS_GEODATABASE_ZIP" -o"$RIS_GEODATABASE" >/dev/null
fi

# Change CWD to this script's directory.
pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

# source the database connection config.
. ../.env

# Last chance to kill script... just in case
(>&2 echo "PostgreSQL Server: ${PGHOST}:${PGPORT}")
sleep 3

psql --quiet -c 'TRUNCATE ris.road_inventory_system;'

# Upload the data
ogr2ogr -overwrite -append -preserve_fid -t_srs EPSG:4326 -f \
  PostgreSQL "PG:host=${PGHOST} port=${PGPORT} user=${PGUSER} dbname=${PGDATABASE} password=${PGPASSWORD}" \
  -where "County_Name = '$COUNTY'" \
  ./data/ris/RISDuplicate.gdb -nlt PROMOTE_TO_MULTI -nln 'ris.road_inventory_system';

psql --quiet -c 'CLUSTER ris.road_inventory_system;'

popd >/dev/null
