#!/bin/bash

# sharedstreets-builder requires pbf format

# See:
#   https://wiki.openstreetmap.org/wiki/Osmosis
#   https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.47

set -e
set -a

# https://github.com/pgRouting/osm2pgrouting#tips

cd "$( dirname "${BASH_SOURCE[0]}" )"

# Upstate
osmosis \
	--read-pbf file=./data/new-york.osm.pbf \
  --tf accept-ways highway=* \
	--bounding-box \
      completeWays=yes completeRelations=yes \
      top=46.408 right=-67.159 bottom=41.4129 left=-75.7835 \
	--write-pbf omitmetadata=true file=./data/new-york.upstate.1.osm.pbf

osmosis \
	--read-pbf file=./data/new-york.osm.pbf \
  --tf accept-ways highway=* \
	--bounding-box \
      completeWays=yes completeRelations=yes \
      top=46.408 right=-75.7835 bottom=41.4129 left=-84.408 \
	--write-pbf omitmetadata=true file=./data/new-york.upstate.2.osm.pbf

# Downstate (NYC)
osmosis \
	--read-pbf file=./data/new-york.osm.pbf \
  --tf accept-ways highway=* \
	--bounding-box \
      completeWays=yes completeRelations=yes \
      top=41.4129 right=-67.159 bottom=38.942 left=-70.6422 \
	--write-pbf omitmetadata=true file=./data/new-york.downstate-west.1.osm.pbf

osmosis \
	--read-pbf file=./data/new-york.osm.pbf \
  --tf accept-ways highway=* \
	--bounding-box \
      completeWays=yes completeRelations=yes \
      top=41.4129 right=-70.6422 bottom=38.942 left=-74.1254 \
	--write-pbf omitmetadata=true file=./data/new-york.downstate-west.2.osm.pbf

# Downstate (Long Island)
osmosis \
	--read-pbf file=./data/new-york.osm.pbf \
  --tf accept-ways highway=* \
	--bounding-box \
      completeWays=yes completeRelations=yes \
      top=41.4129 right=-74.1254 bottom=38.942 left=-79.2667 \
	--write-pbf omitmetadata=true file=./data/new-york.downstate-east.1.osm.pbf

osmosis \
	--read-pbf file=./data/new-york.osm.pbf \
  --tf accept-ways highway=* \
	--bounding-box \
      completeWays=yes completeRelations=yes \
      top=41.4129 right=-79.2667 bottom=38.942 left=-84.408 \
	--write-pbf omitmetadata=true file=./data/new-york.downstate-east.2.osm.pbf
