#!/bin/bash

# ./partitionRISGeodatabaseIntoCountyGeoJSONs \
  # --risGeodatabase data/ris/RISDuplicate.gdb \
  # --outDir data/ris/county_geojson

# find data/ris/county_geojson -type f |
  # sort |
  # while read -r f; do
    # ./partitionGeoJSONByBoundingBoxes \
      # --geoJSON "$f" -N8192 --outDir data/ris/county_geojson_partitions
  # done

# find data/ris/county_geojson_partitions -type f |
  # sort |
  # while read -r f; do
    # ../sharedstreets_conflation/shstMatchRIS  "$f" "${f/county_geojson_partitions/shst_matches}"
  # done
