#!/bin/bash

set -e
set -a

if [ "$#" -ne 2 ]; then
  (>&2 echo "USAGE: You must specify the input GeoJSON file path as the 1st CLI argument and the output file path as the 2nd.")
  exit 1
fi

mkdir -p "$( dirname "$2" )"

INF="$( realpath "$1" )"
OUTF="$( readlink -f "$2" )"

echo "$OUTF"

cd "$( dirname "${BASH_SOURCE[0]}" )"

../node_modules/.bin/shst match "$INF" \
  --match-car \
  --follow-line-direction \
  --tile-hierarchy=7 \
  --out="$OUTF"
