#!/bin/bash

set -e
set -a

if [[ "$#" -ne 1 ]]; then
  echo "ERROR: Pass the TMC_Identification file path as the first & only CLI variable."
  exit 1
fi

INFILE_PATH="$1"

if [ ! -f "$INFILE_PATH" ]; then
  (>&2 echo "ERROR: No file found at the TMC_Identification file path.")
  exit 1
fi

pushd "$( dirname "${BASH_SOURCE[0]}" )/" >/dev/null

# source the database connection config.
. ../.env

TABLE_NAME="tmc_identification"

CSV_HEADER="$( head -1 "$INFILE_PATH" )"

psql --quiet \
  -c "BEGIN;" \
  -f ./sql/create_tmc_identification_table.sql \
  -c 'TRUNCATE tmc_identification;' \
  -f <(
    echo "
      COPY $TABLE_NAME ($CSV_HEADER)
        FROM STDIN CSV HEADER;" &&
    cat "$INFILE_PATH" &&
    echo '\.'
  ) \
  -c 'CLUSTER tmc_identification USING tmc_identification_pkey;' \
  -c "COMMIT;"

popd >/dev/null
