#!/bin/bash

set -e

pushd "$( dirname "${BASH_SOURCE[0]}" )/" >/dev/null

# source the database connection config.
. ../../.env

SQL='
  SELECT
      ways.osm_id,
      ways.tag_id,
      ways.length,
      ways.length_m,
      ways.name,
      ways.source,
      ways.target,
      ways.source_osm,
      ways.target_osm,
      ways.cost,
      ways.reverse_cost,
      ways.cost_s,
      ways.reverse_cost_s,
      ways.rule,
      ways.one_way,
      ways.oneway,
      ways.x1,
      ways.y1,
      ways.x2,
      ways.y2,
      ways.maxspeed_forward,
      ways.maxspeed_backward,
      ways.priority,
      osm_ways.nodes
      ways.the_geom
    FROM ways
      LEFT OUTER JOIN osm_ways USING (osm_id)
  ;
'

ogr2ogr -s_srs EPSG:4326 -t_srs EPSG:4326 -f GeoJSON /vsistdout/ \
  "PG:host=${PGHOST} port=${PGPORT} user=${PGUSER} dbname=${PGDATABASE} password=${PGPASSWORD}" \
  -sql "$SQL" | jq -c '.features[]'

popd >/dev/null
