#!/bin/bash

set -e

pushd "$( dirname "${BASH_SOURCE[0]}" )/" >/dev/null

# source the database connection config.
. ../../.env

SQL='
  SELECT
      tmc,
      type,
      roadnumber,
      roadname,
      firstname,
      lineartmc,
      country,
      state,
      county,
      zip,
      direction,
      startlat,
      startlong,
      endlat,
      endlong,
      miles,
      frc,
      wkb_geometry
    FROM public.npmrds_extended_shapefile
  ;
'

ogr2ogr -s_srs EPSG:4326 -t_srs EPSG:4326 -f GeoJSON /vsistdout/ \
  "PG:host=${PGHOST} port=${PGPORT} user=${PGUSER} dbname=${PGDATABASE} password=${PGPASSWORD}" \
  -sql "$SQL" | jq -c '.features[]'

popd >/dev/null
