#!/usr/bin/env node

/* eslint no-restricted-syntax: 0, no-await-in-loop: 0 */

const targetMapsSQLiteService = require('../../services/targetMapsSQLiteService');
const shstMatchesSQLiteService = require('../../services/shstMatchesSQLiteService');

const makeNpmrdsShstMatchesAsyncIterator = require('./makeNpmrdsShstMatchesAsyncIterator');

const loadMatchesForNpmrdsYearMap = async targetMap => {
  const targetMapFeaturesIterator = targetMapsSQLiteService.makeGeoProximityFeatureIterator(
    targetMap
  );

  const npmrdsShstMatcher = makeNpmrdsShstMatchesAsyncIterator({
    targetMap,
    targetMapFeaturesIterator
  });

  for await (const { shstMatchedFeatures } of npmrdsShstMatcher) {
    shstMatchesSQLiteService.insertFeatures(shstMatchedFeatures);
  }
};

(async () => {
  try {
    const targetMaps = targetMapsSQLiteService.getTargetMapsList();

    const npmrdsTargetMaps = targetMaps.filter(targetMap =>
      /^npmrds_\d{4}$/.test(targetMap)
    );

    for (let i = 0; i < npmrdsTargetMaps.length; ++i) {
      const targetMap = npmrdsTargetMaps[i];
      await loadMatchesForNpmrdsYearMap(targetMap);
    }
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
