#!/usr/bin/env node

const { isAbsolute, basename, join } = require('path');
const yargs = require('yargs');
const recursive = require('recursive-readdir');
const tmp = require('tmp');

const TargetMapLoadingWorkDatabaseService = require('../TargetMapLoadingWorkDatabaseService');

const loadTargetMapFeaturesIntoWorkDatabase = require('./loadTargetMapFeaturesIntoWorkDatabase');
const addMesoLevelPropertiesToTargetMapFeatures = require('./addMesoLevelPropertiesToTargetMapFeatures');
const loadTargetMapFeaturesIntoPermanentDatabase = require('../loadTargetMapFeaturesIntoPermanentDatabase');

const cliArgsSpec = {
  data_dir: {
    demand: true,
    type: 'string'
  }
};

const { argv } = yargs
  .strict()
  .parserConfiguration({
    'camel-case-expansion': false,
    'flatten-duplicate-arrays': false
  })
  .wrap(yargs.terminalWidth() / 1.618)
  .option(cliArgsSpec);

const { data_dir } = argv;

const dataDirAbs = isAbsolute(data_dir)
  ? data_dir
  : join(process.cwd(), data_dir);

const ignoreAllFilesExceptYearNDJSON = (file, stats) => {
  return stats.isFile() && !basename(file).match(/^npmrds\.\d{4}\.ndjson\.gz$/);
};

(async () => {
  try {
    const ndjsonGzFiles = await recursive(dataDirAbs, [
      ignoreAllFilesExceptYearNDJSON
    ]);

    ndjsonGzFiles.sort();

    for (let i = 0; i < ndjsonGzFiles.length; ++i) {
      const filePath = ndjsonGzFiles[i];

      const fileBaseName = basename(filePath);
      const [year] = fileBaseName.match(/\d{4}/);

      const targetMap = `npmrds_${year}`;

      const { name: tmpSQLiteDirPath, removeCallback: cleanup } = tmp.dirSync({
        // dir: join(__dirname, '../../../tmpsqlite/'),
        unsafeCleanup: true
      });

      const dbService = new TargetMapLoadingWorkDatabaseService(
        targetMap,
        tmpSQLiteDirPath
      );

      // eslint-disable-next-line no-await-in-loop
      await loadTargetMapFeaturesIntoWorkDatabase(dbService, filePath);

      addMesoLevelPropertiesToTargetMapFeatures(dbService);

      loadTargetMapFeaturesIntoPermanentDatabase(dbService);

      cleanup();
    }
  } catch (err) {
    if (err.code === 'ENOENT') {
      console.error(
        `ERROR: The provided data_dir, ${data_dir}, does not exist.`
      );
      process.exit(1);
    } else {
      throw err;
    }
  }
})();
