BEGIN;

CREATE SCHEMA IF NOT EXISTS ris;

CREATE TABLE IF NOT EXISTS ris.road_inventory_system (
    ogc_fid                       INTEGER PRIMARY KEY,
    region                        INTEGER,
    gis_id                        INTEGER,
    dot_id                        INTEGER,
    direction                     INTEGER,
    region_co                     INTEGER,
    fips_co                       INTEGER,
    county_name                   CHARACTER VARYING(255),
    county                        CHARACTER VARYING(255),
    route                         CHARACTER VARYING(255),
    signing                       CHARACTER VARYING(255),
    route_no                      INTEGER,
    suffix                        CHARACTER VARYING(255),
    co_rd                         CHARACTER VARYING(255),
    road_name                     CHARACTER VARYING(255),
    begin_description             CHARACTER VARYING(255),
    end_description               CHARACTER VARYING(255),
    county_order                  INTEGER,
    beg_mp                        DOUBLE PRECISION,
    end_mp                        DOUBLE PRECISION,
    section_length                DOUBLE PRECISION,
    muni_geocode                  INTEGER,
    muni_type                     CHARACTER VARYING(255),
    muni_name                     CHARACTER VARYING(255),
    jurisdiction                  CHARACTER VARYING(255),
    owning_jurisdiction           CHARACTER VARYING(255),
    muni_owner_geocode            INTEGER,
    muni_owner_type               CHARACTER VARYING(255),
    muni_owner_name               CHARACTER VARYING(255),
    functional_class              INTEGER,
    federal_aid_highway__stp_er_  CHARACTER VARYING(255),
    nhs_value                     CHARACTER VARYING(255),
    "primary"                     CHARACTER VARYING(255),
    f1991_fed_aid_primary         CHARACTER VARYING(255),
    strahnet                      CHARACTER VARYING(255),
    urban_area_code_id            INTEGER,
    urban_area_name               CHARACTER VARYING(255),
    hpms_ua_code                  INTEGER,
    mpo_desc                      CHARACTER VARYING(255),
    overlap_id                    CHARACTER VARYING(255),
    overlap_hierarchy             INTEGER,
    ris_divided_area_id           INTEGER,
    hpms_sample_id                INTEGER,
    sh_num                        CHARACTER VARYING(255),
    ref_marker                    CHARACTER VARYING(255),
    residency                     CHARACTER VARYING(255),
    total_lanes                   INTEGER,
    primary_dir_lanes             INTEGER,
    divided                       CHARACTER VARYING(255),
    oneway                        CHARACTER VARYING(255),
    access_control                CHARACTER VARYING(255),
    scenic_byway                  CHARACTER VARYING(255),
    trail_crossing                CHARACTER VARYING(255),
    toll                          CHARACTER VARYING(255),
    toll_facility                 CHARACTER VARYING(255),
    parkway                       CHARACTER VARYING(255),
    grouped_road_flag             CHARACTER VARYING(255),
    rest_area                     CHARACTER VARYING(255),
    discontinuous_road_flag       CHARACTER VARYING(255),
    reservation_desc              CHARACTER VARYING(255),
    tandem_truck                  CHARACTER VARYING(255),
    bin_number                    CHARACTER VARYING(255),
    bridge_disp_desc              CHARACTER VARYING(255),
    extra_bridges                 CHARACTER VARYING(255),
    hov                           CHARACTER VARYING(255),
    hov_lanes                     INTEGER,
    railroad_crossing             CHARACTER VARYING(255),
    area                          CHARACTER VARYING(255),
    culture                       CHARACTER VARYING(255),
    passing                       INTEGER,
    parking                       CHARACTER VARYING(255),
    posted_speed_limit            INTEGER,
    ccstn                         INTEGER,
    station_num                   INTEGER,
    aadt_current_yr_est           INTEGER,
    aadt_actual                   INTEGER,
    last_actual_cntyr             INTEGER,
    ddhv                          INTEGER,
    ddhv_factor                   INTEGER,
    adj_cap                       INTEGER,
    v_c                           DOUBLE PRECISION,
    avg_pct_trucks                INTEGER,
    actual_pct_trucks             INTEGER,
    actual_pct_year               INTEGER,
    total_through_lane_width      DOUBLE PRECISION,
    pavement_type_value           CHARACTER VARYING(255),
    shoulder_width                DOUBLE PRECISION,
    shoulder_type                 CHARACTER VARYING(255),
    median_width                  INTEGER,
    median_type                   CHARACTER VARYING(255),
    base                          CHARACTER VARYING(255),
    sub_base_type                 CHARACTER VARYING(255),
    last_overlay                  DOUBLE PRECISION,
    crack_seal_yr                 INTEGER,
    work_yr                       INTEGER,
    work_type                     CHARACTER VARYING(255),
    yr_scored                     INTEGER,
    ss_2007                       CHARACTER VARYING(255),
    ss_2008                       CHARACTER VARYING(255),
    ss_2009                       CHARACTER VARYING(255),
    ss_2010                       CHARACTER VARYING(255),
    ss_2011                       CHARACTER VARYING(255),
    ss_2012                       CHARACTER VARYING(255),
    ss_2013                       CHARACTER VARYING(255),
    ss_2014                       CHARACTER VARYING(255),
    ss_2015                       CHARACTER VARYING(255),
    ss_2016                       CHARACTER VARYING(255),
    ss_2017                       CHARACTER VARYING(255),
    dom_distr                     CHARACTER VARYING(255),
    iri                           INTEGER,
    iri_year                      INTEGER,
    i_rut_depth                   DOUBLE PRECISION,
    rut_year                      INTEGER,
    i_no_of_bumps                 INTEGER,
    bump_cnt_year                 INTEGER,
    max_bump_height               DOUBLE PRECISION,
    bump_max_year                 INTEGER,
    avg_bump_height               DOUBLE PRECISION,
    bump_avg_year                 INTEGER,
    pci                           INTEGER,
    roadway_type                  CHARACTER VARYING(255),
    onramp_from_roadway           CHARACTER VARYING(255),
    offramp_from_roadway          CHARACTER VARYING(255),
    ramp_interchange_code         CHARACTER VARYING(255),
    ramp_alpha_suffix             CHARACTER VARYING(255),
    ramp_orig_dot_id              CHARACTER VARYING(255),
    ramp_orig_co_order            INTEGER,
    ramp_orig_mp                  DOUBLE PRECISION,
    ramp_dest_dot_id              CHARACTER VARYING(255),
    ramp_dest_co_order            INTEGER,
    ramp_dest_mp                  DOUBLE PRECISION,
    segment_type                  CHARACTER VARYING(255),
    k_factor                      DOUBLE PRECISION,
    d_factor                      DOUBLE PRECISION,
    percent_peak_single_unit      DOUBLE PRECISION,
    percent_peak_combp            DOUBLE PRECISION,
    aadt_single_unit              INTEGER,
    aadt_combo                    INTEGER,
    pavement_layer                INTEGER,
    shape_length                  DOUBLE PRECISION,
    wkb_geometry                  public.geometry(MultiLineStringZM,4326)
);

CREATE INDEX IF NOT EXISTS road_inventory_system_geom_idx
  ON ris.road_inventory_system
  USING GIST (wkb_geometry)
;

CLUSTER ris.road_inventory_system USING road_inventory_system_geom_idx;

--  CREATE OR REPLACE VIEW ris.road_inventory_system_2d AS
  --  SELECT 
    --  ogc_fid,
    --  region,
    --  gis_id,
    --  dot_id,
    --  direction,
    --  region_co,
    --  fips_co,
    --  county_name,
    --  county,
    --  route,
    --  signing,
    --  route_no,
    --  suffix,
    --  co_rd,
    --  road_name,
    --  begin_description,
    --  end_description,
    --  county_order,
    --  beg_mp,
    --  end_mp,
    --  section_length,
    --  muni_geocode,
    --  muni_type,
    --  muni_name,
    --  jurisdiction,
    --  owning_jurisdiction,
    --  muni_owner_geocode,
    --  muni_owner_type,
    --  muni_owner_name,
    --  functional_class,
    --  federal_aid_highway__stp_er_,
    --  nhs_value,
    --  "primary",
    --  f1991_fed_aid_primary,
    --  strahnet,
    --  urban_area_code_id,
    --  urban_area_name,
    --  hpms_ua_code,
    --  mpo_desc,
    --  overlap_id,
    --  overlap_hierarchy,
    --  ris_divided_area_id,
    --  hpms_sample_id,
    --  sh_num,
    --  ref_marker,
    --  residency,
    --  total_lanes,
    --  primary_dir_lanes,
    --  divided,
    --  oneway,
    --  access_control,
    --  scenic_byway,
    --  trail_crossing,
    --  toll,
    --  toll_facility,
    --  parkway,
    --  grouped_road_flag,
    --  rest_area,
    --  discontinuous_road_flag,
    --  reservation_desc,
    --  tandem_truck,
    --  bin_number,
    --  bridge_disp_desc,
    --  extra_bridges,
    --  hov,
    --  hov_lanes,
    --  railroad_crossing,
    --  area,
    --  culture,
    --  passing,
    --  parking,
    --  posted_speed_limit,
    --  ccstn,
    --  station_num,
    --  aadt_current_yr_est,
    --  aadt_actual,
    --  last_actual_cntyr,
    --  ddhv,
    --  ddhv_factor,
    --  adj_cap,
    --  v_c,
    --  avg_pct_trucks,
    --  actual_pct_trucks,
    --  actual_pct_year,
    --  total_through_lane_width,
    --  pavement_type_value,
    --  shoulder_width,
    --  shoulder_type,
    --  median_width,
    --  median_type,
    --  base,
    --  sub_base_type,
    --  last_overlay,
    --  crack_seal_yr,
    --  work_yr,
    --  work_type,
    --  yr_scored,
    --  ss_2007,
    --  ss_2008,
    --  ss_2009,
    --  ss_2010,
    --  ss_2011,
    --  ss_2012,
    --  ss_2013,
    --  ss_2014,
    --  ss_2015,
    --  ss_2016,
    --  ss_2017,
    --  dom_distr,
    --  iri,
    --  iri_year,
    --  i_rut_depth,
    --  rut_year,
    --  i_no_of_bumps,
    --  bump_cnt_year,
    --  max_bump_height,
    --  bump_max_year,
    --  avg_bump_height,
    --  bump_avg_year,
    --  pci,
    --  roadway_type,
    --  onramp_from_roadway,
    --  offramp_from_roadway,
    --  ramp_interchange_code,
    --  ramp_alpha_suffix,
    --  ramp_orig_dot_id,
    --  ramp_orig_co_order,
    --  ramp_orig_mp,
    --  ramp_dest_dot_id,
    --  ramp_dest_co_order,
    --  ramp_dest_mp,
    --  segment_type,
    --  k_factor,
    --  d_factor,
    --  percent_peak_single_unit,
    --  percent_peak_combp,
    --  aadt_single_unit,
    --  aadt_combo,
    --  pavement_layer,
    --  shape_length,
    --  ST_Force2D(wkb_geometry) AS wkb_geometry
  --  FROM ris.road_inventory_system
--  ;

COMMIT;
