BEGIN;

CREATE SCHEMA IF NOT EXISTS ris;

CREATE TABLE IF NOT EXISTS ris.road_inventory_system (
    ogc_fid                       INTEGER PRIMARY KEY,
    region                        INTEGER,
    gis_id                        INTEGER,
    dot_id                        INTEGER,
    direction                     INTEGER,
    region_co                     INTEGER,
    fips_co                       INTEGER,
    county_name                   CHARACTER VARYING(255),
    county                        CHARACTER VARYING(255),
    route                         CHARACTER VARYING(255),
    signing                       CHARACTER VARYING(255),
    route_no                      INTEGER,
    suffix                        CHARACTER VARYING(255),
    co_rd                         CHARACTER VARYING(255),
    road_name                     CHARACTER VARYING(255),
    begin_description             CHARACTER VARYING(255),
    end_description               CHARACTER VARYING(255),
    county_order                  INTEGER,
    beg_mp                        DOUBLE PRECISION,
    end_mp                        DOUBLE PRECISION,
    section_length                DOUBLE PRECISION,
    muni_geocode                  INTEGER,
    muni_type                     CHARACTER VARYING(255),
    muni_name                     CHARACTER VARYING(255),
    jurisdiction                  CHARACTER VARYING(255),
    owning_jurisdiction           CHARACTER VARYING(255),
    muni_owner_geocode            INTEGER,
    muni_owner_type               CHARACTER VARYING(255),
    muni_owner_name               CHARACTER VARYING(255),
    functional_class              INTEGER,
    federal_aid_highway__stp_er_  CHARACTER VARYING(255),
    nhs_value                     CHARACTER VARYING(255),
    "primary"                     CHARACTER VARYING(255),
    f1991_fed_aid_primary         CHARACTER VARYING(255),
    strahnet                      CHARACTER VARYING(255),
    urban_area_code_id            INTEGER,
    urban_area_name               CHARACTER VARYING(255),
    hpms_ua_code                  INTEGER,
    mpo_desc                      CHARACTER VARYING(255),
    overlap_id                    CHARACTER VARYING(255),
    overlap_hierarchy             INTEGER,
    ris_divided_area_id           INTEGER,
    hpms_sample_id                INTEGER,
    sh_num                        CHARACTER VARYING(255),
    ref_marker                    CHARACTER VARYING(255),
    residency                     CHARACTER VARYING(255),
    total_lanes                   INTEGER,
    primary_dir_lanes             INTEGER,
    divided                       CHARACTER VARYING(255),
    oneway                        CHARACTER VARYING(255),
    access_control                CHARACTER VARYING(255),
    scenic_byway                  CHARACTER VARYING(255),
    trail_crossing                CHARACTER VARYING(255),
    toll                          CHARACTER VARYING(255),
    toll_facility                 CHARACTER VARYING(255),
    parkway                       CHARACTER VARYING(255),
    grouped_road_flag             CHARACTER VARYING(255),
    rest_area                     CHARACTER VARYING(255),
    discontinuous_road_flag       CHARACTER VARYING(255),
    reservation_desc              CHARACTER VARYING(255),
    tandem_truck                  CHARACTER VARYING(255),
    bin_number                    CHARACTER VARYING(255),
    bridge_disp_desc              CHARACTER VARYING(255),
    extra_bridges                 CHARACTER VARYING(255),
    hov                           CHARACTER VARYING(255),
    hov_lanes                     INTEGER,
    railroad_crossing             CHARACTER VARYING(255),
    area                          CHARACTER VARYING(255),
    culture                       CHARACTER VARYING(255),
    passing                       INTEGER,
    parking                       CHARACTER VARYING(255),
    posted_speed_limit            INTEGER,
    ccstn                         INTEGER,
    station_num                   INTEGER,
    aadt_current_yr_est           INTEGER,
    aadt_actual                   INTEGER,
    last_actual_cntyr             INTEGER,
    ddhv                          INTEGER,
    ddhv_factor                   INTEGER,
    adj_cap                       INTEGER,
    v_c                           DOUBLE PRECISION,
    avg_pct_trucks                INTEGER,
    actual_pct_trucks             INTEGER,
    actual_pct_year               INTEGER,
    total_through_lane_width      DOUBLE PRECISION,
    pavement_type_value           CHARACTER VARYING(255),
    shoulder_width                DOUBLE PRECISION,
    shoulder_type                 CHARACTER VARYING(255),
    median_width                  INTEGER,
    median_type                   CHARACTER VARYING(255),
    base                          CHARACTER VARYING(255),
    sub_base_type                 CHARACTER VARYING(255),
    last_overlay                  DOUBLE PRECISION,
    crack_seal_yr                 INTEGER,
    work_yr                       INTEGER,
    work_type                     CHARACTER VARYING(255),
    yr_scored                     INTEGER,
    ss_2007                       CHARACTER VARYING(255),
    ss_2008                       CHARACTER VARYING(255),
    ss_2009                       CHARACTER VARYING(255),
    ss_2010                       CHARACTER VARYING(255),
    ss_2011                       CHARACTER VARYING(255),
    ss_2012                       CHARACTER VARYING(255),
    ss_2013                       CHARACTER VARYING(255),
    ss_2014                       CHARACTER VARYING(255),
    ss_2015                       CHARACTER VARYING(255),
    ss_2016                       CHARACTER VARYING(255),
    ss_2017                       CHARACTER VARYING(255),
    dom_distr                     CHARACTER VARYING(255),
    iri                           INTEGER,
    iri_year                      INTEGER,
    i_rut_depth                   DOUBLE PRECISION,
    rut_year                      INTEGER,
    i_no_of_bumps                 INTEGER,
    bump_cnt_year                 INTEGER,
    max_bump_height               DOUBLE PRECISION,
    bump_max_year                 INTEGER,
    avg_bump_height               DOUBLE PRECISION,
    bump_avg_year                 INTEGER,
    pci                           INTEGER,
    roadway_type                  CHARACTER VARYING(255),
    onramp_from_roadway           CHARACTER VARYING(255),
    offramp_from_roadway          CHARACTER VARYING(255),
    ramp_interchange_code         CHARACTER VARYING(255),
    ramp_alpha_suffix             CHARACTER VARYING(255),
    ramp_orig_dot_id              CHARACTER VARYING(255),
    ramp_orig_co_order            INTEGER,
    ramp_orig_mp                  DOUBLE PRECISION,
    ramp_dest_dot_id              CHARACTER VARYING(255),
    ramp_dest_co_order            INTEGER,
    ramp_dest_mp                  DOUBLE PRECISION,
    segment_type                  CHARACTER VARYING(255),
    k_factor                      DOUBLE PRECISION,
    d_factor                      DOUBLE PRECISION,
    percent_peak_single_unit      DOUBLE PRECISION,
    percent_peak_combp            DOUBLE PRECISION,
    aadt_single_unit              INTEGER,
    aadt_combo                    INTEGER,
    pavement_layer                INTEGER,
    shape_length                  DOUBLE PRECISION,
    wkb_geometry                  public.geometry(MultiLineString,4326)
);

CREATE INDEX IF NOT EXISTS road_inventory_system_geom_idx
  ON ris.road_inventory_system
  USING GIST (wkb_geometry)
;

CLUSTER ris.road_inventory_system USING road_inventory_system_geom_idx;

COMMIT;
