#!/bin/bash

set -e

# https://wiki.openstreetmap.org/wiki/Osmconvert
# https://github.com/pgRouting/osm2pgrouting#tips

cd "$( dirname "${BASH_SOURCE[0]}" )"
cd ../data/osm/

osmconvert \
  new-york-190101.osm.pbf \
  --drop-author --drop-version \
  --out-pbf -o=new-york.osm.pbf

