const MESO_LEVEL_FEATURES_SORTING_BY_NETWORK_METADATA =
  'MESO_LEVEL_FEATURES_SORTING_BY_NETWORK_METADATA';

const MESO_LEVEL_FEATURES_SORTING_BY_DIRECTION_AND_PROPERTIES =
  'MESO_LEVEL_FEATURES_SORTING_BY_DIRECTION_AND_PROPERTIES';

module.exports = {
  MESO_LEVEL_FEATURES_SORTING_BY_NETWORK_METADATA,
  MESO_LEVEL_FEATURES_SORTING_BY_DIRECTION_AND_PROPERTIES
};
