#!/usr/bin/env node

/* eslint no-continue: 0, no-restricted-syntax: 0, no-param-reassign: 0, */

const { readFileSync } = require('fs');
const { join } = require('path');

const turf = require('@turf/turf');

const conflationMapSQLiteService = require('../services/conflationMapSQLiteService');

const {
  features: [albanyPoly]
} = JSON.parse(
  readFileSync(join(__dirname, './albany_bounding_polygon.geojson'))
);

const iterator = conflationMapSQLiteService.makeConflationMapFeatureIterator();

for (const conflationOutputFeature of iterator) {
  if (turf.booleanContains(albanyPoly, conflationOutputFeature)) {
    console.log('CONTAINS');
  } else {
    console.log('NOPE');
  }
}
